AWSTemplateFormatVersion: 2010-09-09
Description: CI/CD pipeline for GitHub projects

Parameters:
  CodeBuildEnvironmentImage:
    Type: String
    Default: 'aws/codebuild/standard:5.0'
  CodeBuildVPC:
    Type: AWS::EC2::VPC::Id
  CodeBuildSubnet:
    Type: AWS::EC2::Subnet::Id
  CodeBuildSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  ArtifactStoreS3Location:
    Type: String
    Description: Name of the S3 bucket to store CodePipeline artificat.

Resources:
  MyRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: MyDemoRepo
      RepositoryDescription: This is a repository for my project with code from MySourceCodeBucket
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Artifacts:
        Type: S3
        Location:
          Ref: ArtifactStoreS3Location
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: !Ref CodeBuildEnvironmentImage
        EnvironmentVariables:
          - Name: varName1
            Value: varValue1
          - Name: varName2
            Value: varValue2
            Type: PLAINTEXT
      Source:
        Type: GITHUB
        Location: https://github.com/krunalbhoyar/db-migrate.git
      TimeoutInMinutes: 10
      VpcConfig:
        VpcId: !Ref CodeBuildVPC
        Subnets: [!Ref CodeBuildSubnet]
        SecurityGroupIds: [!Ref CodeBuildSecurityGroup]
      Cache:
        Type: S3
        Location: mybucket/prefix
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                - "codecommit:ListBranches"
                - "codecommit:ListRepositories"
                - "codecommit:BatchGetRepositories"
                - "codecommit:Get*"
                - "codecommit:GitPull"
                - "s3:PutObject"
                - "s3:GetObject"
                - "s3:GetObjectVersion"
                - "s3:ListBucket"
                - "ssm:GetParameters"
                Effect: Allow
                Resource: '*'
                
              
